version: "3.9"

services:

  database:
    build:
      network: host
      dockerfile: Dockerfile.database
    image: nathants/webapp:database${suffix:-}
    network_mode: host
    profiles: ["run", "all"]

  backend:
    build:
      network: host
      dockerfile: Dockerfile.backend
    image: nathants/webapp:backend${suffix:-}
    network_mode: host
    profiles: ["run", "all"]

  frontend:
    build:
      network: host
      dockerfile: Dockerfile.frontend
    image: nathants/webapp:frontend${suffix:-}
    network_mode: host
    profiles: ["run", "all"]

  test:
    build:
      network: host
      dockerfile: Dockerfile.test
    image: nathants/webapp:test${suffix:-}
    network_mode: host
    volumes:
      - .:/code
    profiles: ["test", "all"]
