version: "3.9"

services:

  ## run profile

  database:
    build:
      network: host
      dockerfile: Dockerfile.database
    image: nathants/webapp:database${suffix:-}
    network_mode: host
    profiles: ["run", "all"]

  backend:
    build:
      network: host
      dockerfile: Dockerfile.backend
    image: nathants/webapp:backend${suffix:-}
    network_mode: host
    profiles: ["run", "all"]

  frontend:
    build:
      network: host
      dockerfile: Dockerfile.frontend
    image: nathants/webapp:frontend${suffix:-}
    network_mode: host
    profiles: ["run", "all"]

  ## test profile

  test:
    build:
      network: host
      dockerfile: Dockerfile.test
    image: nathants/webapp:test${suffix:-}
    network_mode: host
    volumes:
      - .:/code
    profiles: ["test", "all"]

  ## dev profile

  database-dev:
    image: nathants/webapp:database
    network_mode: host
    profiles: ["dev"]

  backend-dev:
    image: nathants/webapp:backend
    network_mode: host
    entrypoint: ""
    command: bash entrypoint_dev_backend.sh
    volumes:
      - .:/code
    tty: true
    profiles: ["dev"]

  frontend-dev:
    image: nathants/webapp:frontend
    network_mode: host
    entrypoint: ""
    command: bash entrypoint_dev_frontend.sh
    volumes:
      - .:/code
    tty: true
    profiles: ["dev"]

  test-dev:
    image: nathants/webapp:test
    network_mode: host
    entrypoint: ""
    command: bash entrypoint_dev_test.sh
    tty: true
    volumes:
      - .:/code
    profiles: ["dev"]
