version: "3.9"

services:

  kafka:
    build:
      network: host
      dockerfile: extra/Dockerfile.kafka
    image: kafka:latest${suffix:-}
    network_mode: host
    profiles: ["run", "all"]
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://localhost:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: localhost
    command: ["kafka-server-start.sh", "/server.properties"]

  zookeeper:
    build:
      network: host
      dockerfile: extra/Dockerfile.zookeeper
    image: zookeeper:latest${suffix:-}
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    profiles: ["run", "all"]
    command: ["zkServer.sh", "start-foreground"]

  test:
    build:
      network: host
      dockerfile: extra/Dockerfile.test
    image: kafka-test:latest
    network_mode: host
    volumes:
      - .:/code
    profiles: ["test", "all"]
