FROM archlinux:latest

RUN echo 'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist

RUN pacman -Syu --noconfirm go

COPY . /code

WORKDIR /code

RUN go build # build once to fetch go deps and warm compiler cache so later we cant mount -v $(pwd):/code

CMD go run /code/test.go
